### ISSUE TITLE
Not compatible with TB 115

### ISSUE THREAD

**Issue by BillH99999** [tekezo/disable_dnd_tb#5]
I just got updated to TB 115.  I notice that this extension is not compatible with TB 115.   Are you planning to update the extension?.  I am not trying to rush you or anything... I'm just hoping an update will come eventually.

Thanks,
Bill

**Comment by BillH99999** [comment]
I see that version 5.0.0 is now available.  I updated to 5.0.0 and it works fine.  Thanks!

I see that the prompt to allow a move has been removed.  That was what really made the extension great.  Would it be possible to update the extension so that you could hold down a key (Ctrl or Alt for example) and drag to allow the move so that we don't have to disable the extension in order to move a folder?  That would make it much more convenient to use.

Thanks,
Bill

**Comment by bernd-o-mat** [comment]
Hello,
I loved the add-on but it seems that the loss of the prompt is blocking "QuickFolders" (another great TB Add-On) to work as it should. See https://github.com/RealRaven2000/QuickFolders/issues/413
Thanks,
Berndomat

**Comment by tekezo** [comment]
The implementation of the prompt was never very well-behaved to begin with, so it can’t be used in recent versions of Thunderbird. Allowing temporary folder movement with a modifier key is a good idea instead.

I added an option: `Allow the folder movement if drag starts with the shift key pressed.` in v5.2.0.

The new version is under review on the Thunderbird add-on site, but in the meantime, you can download the xpi file from here.
https://github.com/pqrs-org/disable-draganddrop-tb/releases/tag/v5.2.0

<img width="786" alt="Screenshot 2024-05-26 at 15 25 52" src="https://github.com/pqrs-org/disable-draganddrop-tb/assets/659178/f4cdd079-9ee3-4e86-8f4f-ecceb329dffa">
