### ISSUE TITLE
support for Thunderbird 125

### ISSUE THREAD

**Issue by m-i-k-e-y** [tekezo/disable_dnd_tb#6]
First of all thanks for this great addon.

I'm wondering if there are any plans to make this addon compatible with the upcoming Thunderbird 125 and following releases.

**Comment by tekezo** [comment]
I'll support each new release as it comes. I believe the next official release will be 127.

I updated the add-on to support 125 and 127 in version 5.2.0.
The new version is under review on the Thunderbird add-on site, but in the meantime, you can download the xpi file from here.
https://github.com/pqrs-org/disable-draganddrop-tb/releases/tag/v5.2.0
