### ISSUE TITLE
blocking not working in new tab

### ISSUE THREAD

**Issue by kudel** [tekezo/disable_dnd_tb#7]
If you right click on some imap subfolder and select 'open in new tab'.
In new tab drag&drop isn't disabled at all.

**Comment by tekezo** [comment]
Thank you for feedback!
I fixed the issue in v5.3.0. You can download the xpi from here.
https://github.com/pqrs-org/disable-draganddrop-tb/releases/tag/v5.3.0

The v5.3.0 is under review on the Thunderbird add-on site, so it will take a little more time before it gets updated.
https://addons.thunderbird.net/en-US/thunderbird/addon/disable-draganddrop-tb-v2/

**Comment by kudel** [comment]
It's working. Thank you! :)
