### ISSUE TITLE
Support for Thunderbird 128 esr

### ISSUE THREAD

**Issue by BillH99999** [tekezo/disable_dnd_tb#8]
I just updated to TB 128 esr.  The plugin is disabled in 128 esr.  Are you planning on updating it to support TB 128 esr?

Thanks,
Bill

**Comment by tekezo** [comment]
Thank you for feedback!

I released v5.5.0 that supports TB 128 esr.
https://github.com/pqrs-org/disable-draganddrop-tb/releases/tag/v5.5.0

**Comment by BillH99999** [comment]
Thanks!  Works great now in 128.

Bill
